In [1]:
import numpy as np
import pandas as pd

In [6]:
dataset = pd.read_csv('Data_Set.csv')

# Datos de entrada
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values

In [7]:
X[0, :]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [4]:
# Codificar datos categóricos

from sklearn.preprocessing import LabelEncoder
LabelEncoder_X_1 = LabelEncoder()
X[:, 1] = LabelEncoder_X_1.fit_transform(X[:, 1])
LabelEncoder_X_2 = LabelEncoder()
X[:, 2] = LabelEncoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers=[
        ("Data", OneHotEncoder(categories='auto'), [1])
    ], remainder='passthrough'
)
X = transformer.fit_transform(X)
X = X[:, 1:]
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)