In [9]:
import numpy as np
import pandas as pd

In [10]:
dataset = pd.read_csv('Data_Set.csv')

# Datos de entrada
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values

In [11]:
X[0, :]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [12]:
# Codificar datos categóricos

from sklearn.preprocessing import LabelEncoder
LabelEncoder_X_1 = LabelEncoder()
X[:, 1] = LabelEncoder_X_1.fit_transform(X[:, 1])
LabelEncoder_X_2 = LabelEncoder()
X[:, 2] = LabelEncoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers=[
        ("Data", OneHotEncoder(categories='auto'), [1])
    ], remainder='passthrough'
)
X = transformer.fit_transform(X)
X = X[:, 1:]
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
print(x_train)

[[-0.5698444   1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [-0.5698444  -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-0.5698444   1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [ 1.75486502 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]]


In [19]:
#construir red neuronal
import keras
from keras.models import Sequential
from keras.layers import Dense

In [18]:
inicializar = Sequential()
inicializar.add(Dense(units=8, kernel_initializer='uniform',
                activation='relu', input_dim=11))
inicializar.add(
    Dense(units=8, kernel_initializer='uniform', activation='relu'))

# Capa de salida
inicializar.add(
    Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

# Compilar mi red neuronal, valor de pérdida, valor de acertamiento
inicializar.compile(
    optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

inicializar.fit(x_train, y_train, batch_size=10, epochs=10)

Epoch 1/10


AttributeError: module 'keras.src.backend' has no attribute 'convert_to_numpy'